# Generated by Django 5.1.4 on 2024-12-28 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga_produk', models.BigIntegerField()),
                ('stok_produk', models.SmallIntegerField()),
                ('kategori_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='app_toko.kategori')),
            ],
        ),
    ]
